### ISSUE TITLE
How is the same encoding distinguished when used in different types (words, characters, etc.)?

### ISSUE THREAD

**Issue by 0xis-cn** [matthew-davis/bliss-font#1]

**Comment by 0xis-cn** [comment]
Symbol 12321 and 12323 are both `\f101`, with the former is defined in `css/characters.css` and the latter `css/words.css`. How can them be used together?

**Comment by matthew-davis** [comment]
I'm not sure, I abandoned this attempt a year ago or there abouts as I am pretty sure that this is not the way to build a bliss keyboard. I'm pretty sure that my thinking before I paused the project was to use svgs. But I had done some work, so I left it up in the off chance it was useful to someone. So if you fancy taking this work and attempting to move it forward go for it.

**Comment by 0xis-cn** [comment]
Thanks. I will continue your project if possible.

**Comment by matthew-davis** [comment]
Good luck

**Comment by martin12333** [comment]
> _Thanks. I will continue your project if possible._

@0xis-cn 

(BTW, there is also an older font from 2012: CcfSymbolFont ... 5000+ bliss symbols

(and a much smaller font ASEMTOG_F700 ... 190 most common characters)

and a combined font CcfSymbolFont_ASEMTOG_F700

[drive.google.com](https://drive.google.com/drive/folders/1d26WrNzdqhywa2xEeh-XLPK4U5sI6v6w
)
)
